version: "3.9"

services:
  consul:
    image: consul:1.1.0
    hostname: localhost
    ports:
      - 8500:8500
  postgres:
    container_name: bureaucracy_db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=bureaucracy_db
    volumes:
      - bureaucracy_db_data:/var/lib/postgresql/data
    networks:
      - bureaucracy_service

volumes:
  bureaucracy_db_data:
    name: bureaucracy_db_data

networks:
  bureaucracy_service:
    driver: bridge