CREATE TABLE CITIZEN(
    ID BIGINT PRIMARY KEY,
    FIRST_NAME VARCHAR,
    SECOND_NAME VARCHAR,
    DATE_OF_BIRTH DATE
);

CREATE TABLE DOCUMENT(
    ID BIGINT PRIMARY KEY,
    DOCUMENT_TYPE VARCHAR,
    CITIZEN_ID BIGINT,
    NUMBER VARCHAR
);

CREATE TABLE ADDRESS(
    ID BIGINT PRIMARY KEY,
    REGION VARCHAR,
    INDEX INT,
    CITY VARCHAR,
    STREET VARCHAR,
    HOUSE_NUMBER VARCHAR,
    APARTMENT VARCHAR
);

CREATE TABLE REGISTRATION_ADDRESS(
    ADDRESS_ID BIGINT,
    CITIZEN_ID BIGINT
);

ALTER TABLE REGISTRATION_ADDRESS
    ADD CONSTRAINT fk_registration_to_address FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS (ID);

ALTER TABLE REGISTRATION_ADDRESS
    ADD CONSTRAINT fk_registration_to_citizen FOREIGN KEY (CITIZEN_ID) REFERENCES CITIZEN (ID);

ALTER TABLE DOCUMENT
    ADD CONSTRAINT fk_document_citizen FOREIGN KEY (CITIZEN_ID) REFERENCES CITIZEN (ID);
