ALTER TABLE REGISTRATION_ADDRESS RENAME TO CITIZEN_ADDRESS;

ALTER TABLE CITIZEN ADD COLUMN
    REGISTRATION_ADDRESS_ID BIGINT;

ALTER TABLE CITIZEN ADD COLUMN
    PHONE_NUMBER VARCHAR;

ALTER TABLE CITIZEN
    ADD CONSTRAINT fk_citizen_registration_address FOREIGN KEY (REGISTRATION_ADDRESS_ID) REFERENCES ADDRESS (ID);